name: 'SAST Scans'

on:
  pull_request:
  merge_group:

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    env:
      SAST_GH_APP_ID:           ${{ secrets.SAST_GH_APP_ID }}
      SAST_GH_APP_PRIVATE_KEY:  ${{ secrets.SAST_GH_APP_PRIVATE_KEY }}
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id:      ${{ env.SAST_GH_APP_ID }}
          private-key: ${{ env.SAST_GH_APP_PRIVATE_KEY }}
      - name: Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v2.1.0
        with:
          token:          ${{ steps.app-token.outputs.token }}
          fail-on-alert:  true
          fail-on-alert-exclude-closed: true

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          fail-on-severity: high
