name: Security Alert Summary

# Managed by github-infra. Do not update this file directly.
# To make changes, update the file in the github-infra repository.

on:
  pull_request:
    branches:
      - master
      - main
      - develop

concurrency:
  group: security-alert-summary-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-alert-summary:
    if: github.actor != 'dependabot[bot]'
    uses: HeadspaceMeditation/github-infra/.github/workflows/security-alert-summary-reusable.yml@master
    with:
      pr_number: ${{ github.event.pull_request.number }}
    secrets: inherit
