name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==1.3.1"

      - name: Run tests with nox
        run: |
          poetry run nox --python ${{ matrix.python }}

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Setup git
        run: |
          git config user.name release-transformer-embeddings
          git config user.email transformer-embeddings@headspace.com

      - name: Install Poetry, dependencies, release
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi --only release
          poetry run semantic-release publish
